### ISSUE TITLE
How to set the TNT drop?I want to set it to 25%, but I can't find it in spigot.yml

### ISSUE THREAD

**Issue by Noogear** [Spimy/QoLTweaks#1]
How to set the TNT drop?I want to set it to 25%, but I can't find it in spigot.yml
![QQ截图20230217003658](https://user-images.githubusercontent.com/123232885/219429723-02a82fd6-e355-4230-a908-e4a0690b27c9.jpg)

**Comment by Spimy** [comment]
Run the server with the plugin and go to `plugins/QoLTWeaks/modules/blocks/tnt-drop-rate.yml` and edit the drop rate to fit your needs. The drop rate is in percentage (for e.g. 1.0 is 100%). After you have changed the config there, either restart your server or run `/qol reload`.

**Comment by RAURORA2** [comment]
> 使用插件运行服务器，然后转到并编辑丢弃率以满足您的需求。下降率以百分比表示（例如 1.0 为 100%）。在此处更改配置后，重新启动服务器或运行。`plugins/QoLTWeaks/modules/blocks/tnt-drop-rate.yml``/qol reload`

I'm just curious where did the 25% statement come from

**Comment by Noogear** [comment]
> Run the server with the plugin and go to and edit the drop rate to fit your needs. The drop rate is in percentage (for e.g. 1.0 is 100%). After you have changed the config there, either restart your server or run .`plugins/QoLTWeaks/modules/blocks/tnt-drop-rate.yml``/qol reload`

I'm just curious where did the 25% statement come from

**Comment by Spimy** [comment]
In spigot, the default TNT drop rate is 25%.
